[package]
name = "admin_tools"
version = "0.1.0"
authors = ["Sam Mohr <sm185543@ncr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgi = "0.2"
mysql = "16"
dotenv = "0.14.1"
